### ISSUE TITLE
Ajuste no README.md 

### ISSUE THREAD

**Issue by bragaped** [HashLoad/jhonson#10]
No DelphiXE7 ao tentar utilizar o código
   THorse.Use( Jhonson );
Gera um erro de compilação informando que a variável está inválida
![image](https://user-images.githubusercontent.com/63470736/107229100-2a764080-69fc-11eb-81e5-7cc8e67f41ef.png)

A solução é bem simples basta colocar o parênteses ao informar o uso do Jhonson.

THorse.Use( Jhonson() );

Com Isso sugiro rever os Middleware oficiais como o horse-compression por exemplo que também faz menção a forma de uso que apresenta erro.

**Comment by viniciussanchez** [comment]
Obrigado pela informação...
Não quer ajudar na documentação enviando um Pull Request com as melhorias?

**Comment by bragaped** [comment]
Assim que liberar aqui na empresa faço a criação e envio dos ajustes nos Middlewares Oficiais.

**Comment by bragaped** [comment]
Ajustes enviados para os Middleware Oficiais.
