### ISSUE TITLE
Horse 3.01 

### ISSUE THREAD

**Issue by servtelpro** [HashLoad/jhonson#14]
Horse.OctetStream.pas(54): E2003 Undeclared identifier: 'THorseHackRequest'

**Comment by juliomar** [comment]
tentou instalar a dependencia?
https://github.com/HashLoad/horse-octet-stream

**Comment by viniciussanchez** [comment]
🇺🇸:
@servtelpro you can see from the error message, that it doesn't belong to this middleware. It belongs to the Stream middleware. However, the THorseHackRequest class no longer exists, and the middleware is already working perfectly. Most likely you must have outdated code or did something wrong there.
--
🇧🇷: 
@servtelpro pode ver pela mensagem do erro, que o este não pertence a este middleware. Pertence ao middleware de Stream. Porém, a classe THorseHackRequest não existe mais, e o middleware já esta funcionando perfeitamente. Muito provavelmente você deve estar com código desatualizado ou fez alguma coisa de errado ai.
