### ISSUE TITLE
Acentuação Linux

### ISSUE THREAD

**Issue by WhebertonFialho** [HashLoad/jhonson#15]
mesmo configurado o jhonson com "UFT-8" a acentuação esta sendo substituido por "?"

**Comment by viniciussanchez** [comment]
Está com os fontes atualizados? Qual a versão do Delphi / Lazarus?

**Comment by WhebertonFialho** [comment]
SIm, ja estou na versao 1.1.4

delphi 10.4

![image](https://user-images.githubusercontent.com/9007678/175042448-a0ef97d0-e404-488e-aa3c-c837bcc7230d.png)

**Comment by WhebertonFialho** [comment]
Bom Dia, Ainda não consegui e ja configurei "utf-8",  " ISO-8859-1"  e " ISO-8859-15" e mesmo assim ainda nao consegue solucionar;

**Comment by dliocode** [comment]
Se testar pelo postman, vem com a acentuação errada?

**Comment by viniciussanchez** [comment]
@WhebertonFialho conseguiu resolver o problema?

**Comment by CarlosHe** [comment]
Esse erro de acentuação só ocorre com dados que são obtidos do banco de dados?

Preciso de alguns detalhes pra tentar descobrir o que pode ser:

- Conector do banco de dados (FireDAC, UniDAC, MyDAC, Zeos...)
- Banco de dados (PostgreSQL, MySQL, MariaDB...)

**Comment by CarlosHe** [comment]
Esse erro de acentuação só ocorre com dados que são obtidos do banco de dados?

Preciso de alguns detalhes pra tentar descobrir o que pode ser:

- Conector do banco de dados (FireDAC, UniDAC, MyDAC, Zeos...)
- Banco de dados (PostgreSQL, MySQL, MariaDB...)
- Charset do banco/tabela
- Charset definido no conector

**Comment by UnisystemGIT** [comment]
Não consegui resolver, para liberar eu retirei todas a acentuação do meu front-end;

Conector FireDAC;
Banco de Dados Oracle;
Charset Banco/Tabela WE8MSWIN1252;
Charset conector UTF-8;

**Comment by muriloSantanaAraujo** [comment]
Olá,  estou com o delphi 10.3  e utilizando as uma das primeiras versão do jhonson e do horse, tive o mesmo problema que a versão delphi.  È simples resolve, na versão que estou o System.JSON.TJSonValue.Tojson  não converte corretamente o caracters utf8 você precisa utiliza   System.JSON.TJSonValue.ToString ; 

o jhonson já verifica a compiler version para tratar isso só ajustar para a sua versão : https://docwiki.embarcadero.com/RADStudio/Alexandria/en/Compiler_Versions 

no finally do  middleware ajustei o compilerVersion ser maior que a minha versão  10.3(33.0) 
` Res.RawWebResponse.Content := {$IF CompilerVersion > 33.0}TJSONValue(Res.Content).ToJSON{$ELSE}TJSONValue(Res.Content).ToString{$ENDIF};`

 Para o Delphi 10.4 o compilerversion seria 34.0

**Comment by augustolpq** [comment]
Corrigi o meu trocando o characterset do fdconnection para "latin1". Uso mysql 5.7.29
