### ISSUE TITLE
Erro ao compilar no delphi Seatle

### ISSUE THREAD

**Issue by energyinfo** [HashLoad/jhonson#16]
Ocorre um erro ao compilar no Delphi Seatle na seguinte linha:

procedure Middleware(Req: THorseRequest; Res: THorseResponse; Next: {$IF DEFINED(FPC)}TNextProc{$ELSE}TProc{$ENDIF});
var
  LJSON: {$IF DEFINED(FPC)}TJsonData{$ELSE}TJSONValue{$ENDIF};
begin
//  if (Req.MethodType in [mtPost, mtPut, mtPatch]) and (Req.RawWebRequest.ContentType.Contains('application/json')) then
  if (Req.MethodType in [mtPost, mtPut, mtPatch]) and (pos('application/json',Req.RawWebRequest.ContentType)>0) then

Resolvi desta forma, porém não sei se é a ideal.

**Comment by viniciussanchez** [comment]
@energyinfo poderia mandar um print do erro? Imagino que o problema seja o .Contains que não vai ter na sua versão do Delphi. Porém, o Pos que você usou também resolveria. Se quiser mandar um pull request com a correção...
