### ISSUE TITLE
Erro ao tentar instalar o Middlewares jhonson.  🆘 

### ISSUE THREAD

**Issue by alrtecnologia** [HashLoad/jhonson#17]
Olá pessoal ao tentar instalar o  Middlewares jhonson estou recebendo uma msg de erro que não sei oque esteja causando. 

❯❯ backend  13:20 boss install jhonson
[WARN ] Please restart your console after complete.
[INFO ] Installing modules in project path
[INFO ] Building cache files...
[INFO ] Updating cache of dependency horse
[INFO ] Updating cache of dependency jhonson
[INFO ] Installing modules
[INFO ] Processing dependency horse
[WARN ] Tag not found , using semantic now...
[WARN ]   No candidate to version for ^3.1.6. Using master branch
[ERROR]   Error on switch to needed version from dependency github.com/hashload/horse

![image](https://github.com/HashLoad/jhonson/assets/131351216/d53775d4-da97-48f7-a52f-f8697bb74057)
---

- boss version: [v3.0.12](https://github.com/HashLoad/boss/releases/tag/v3.0.12)

**Comment by viniciussanchez** [comment]
Estranho... o erro ainda persiste? Tentou remover o cache do boss? Fez login no github com ssh?

**Comment by alrtecnologia** [comment]
Opa @viniciussanchez, foram feitas todas as sugestões que vc mencionou e o problema continuava. Porem ao persistir com a tentativa de instalação,  depois de imprimir o mesmo error anterior,  meu terminal não encerrou o processo e após aguardar uns 10 minutos ele instalou o middleware.
