### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by giulianon** [HashLoad/jhonson#5]
Conforme postei no grupo do telegram da hasload, o Jhonson faz o parser mas não valida o json.
Para validar faltaria chamar o LJSON.toJSON e caso falhe já devolveria um status 400 automaticamente.
Enviei um vídeo exemplificando para o Vinicius.

**Comment by viniciussanchez** [comment]
@giulianon não quer fazer a implementação e enviar o PR?

**Comment by giulianon** [comment]
Fiz o ajuste.

Segue anexo.

[jhonson-master.zip](https://github.com/HashLoad/jhonson/files/5109350/jhonson-master.zip)

**Comment by CarlosHe** [comment]
Olhei o arquivo, acho que vou ter algumas observações para fazer! Mais tarde vejo com mais calma, vou analisar melhor!

**Comment by giulianon** [comment]
Tranquilo Carlos.

**Comment by viniciussanchez** [comment]
@CarlosHe qual seria as observações para gente matar essa issue tambem?

**Comment by viniciussanchez** [comment]
@giulianon basicamente essa aqui foram as suas mudanças, correto?

```pascal
  if (LWebRequest.MethodType in [mtPost, mtPut]) and (LWebRequest.ContentType = 'application/json') then
  begin
    LJSON := TJSONObject.ParseJSONValue(Req.Body);
    try
      LJSON.ToJSON;
      THorseHackRequest(Req).SetBody(LJSON);
    except
      try
        LParseError := TJSONObject.Create;
        LParseError.AddPair('error', 'Parse json error');
        LParseError.AddPair('description', 'Invalid json');
        Res.Send(LParseError.ToJSON).Status(THTTPStatus.BadRequest);
      finally
        LParseError.Free;
      end;
      raise EHorseCallbackInterrupted.Create;
    end;
  end;
```
